54 show story after submitting the form
chingu-voyages/v43-tier1-team-08 pull request #56
Opened 2023-03-24 01:11 UTC by ss-deep

## Description

 -Initially page displays the form with 'Submit' and 'Reset' buttons.
 -After clicking on 'Submit', story is displayed in place of form.
 -Goes back to 'Form' when clicked on button 'Play Again'.

(It needs styling to look neat and nice.)

## Related Issue

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
|     | :sparkles: New feature     |
| ✓ | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

### After

![](https://cdn.discordapp.com/attachments/1084884575265763489/1088119235089272954/Screenshot_2023-03-22_at_10.11.47_AM.png)

![](https://cdn.discordapp.com/attachments/1084884575265763489/1088119235340947456/Screenshot_2023-03-22_at_10.08.38_AM.png)

## Testing Steps / QA Criteria

2023-03-24 01:35 UTC, terrifricker commented on style.css
> +    font-family: Verdana, Geneva, Tahoma, sans-serif;
great change!

2023-03-24 01:39 UTC, terrifricker commented on style.css
>      font-size: 1.2rem;
Could take font-family out of here because it is now in body.

2023-03-24 01:54 UTC, ss-deep commented on style.css
>      font-size: 1.2rem;
oh, missed it. i will change.

2023-03-24 14:58 UTC, ss-deep commented on style.css
> +    font-family: Verdana, Geneva, Tahoma, sans-serif;
Thanks

2023-03-25 16:46 UTC, terrifricker commented on second.html
> +                        <button type="reset">Reset</button>
Good catch!

2023-03-25 18:17 UTC, terrifricker requested changes
It's looking so good, @ss-deep 

I've sent you files with comments about your javascript through discord.  Your reset button is perfect!  Your logic for using display: none; is perfect, too.  I just suggest that instead of adding display: none; to your story class, you create a new class called hidden.

```
hidden {
    display: none;
}
```
adding and removing 'hidden' from the classLists of the form and story instead.

For the first time, I figured out how to make the suggestions right in the code, so you can just click a button to accept the changes one by one, or even as a batch all together.  The instructions are found at: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

2023-03-25 18:17 UTC, terrifricker commented on app.js
> +    wordForm.classList.add('story');
```suggestion
    wordForm.classList.add('hidden');
```

2023-03-25 18:17 UTC, terrifricker commented on app.js
> +    story.classList.remove('story');
```suggestion
    story.classList.remove('hidden');
```

2023-03-25 18:17 UTC, terrifricker commented on app.js
> +    story.classList.add('story');
```suggestion
    story.classList.add('hidden');
```

2023-03-25 18:17 UTC, terrifricker commented on app.js
> +    wordForm.classList.remove('story');
```suggestion
    wordForm.classList.remove('hidden');
```

2023-03-25 18:17 UTC, terrifricker commented on second.html
> +                <form class="input-form" name="input-form" action="#">
Using a name attribute on a form was new to me.  I learned something.

2023-03-25 18:17 UTC, terrifricker commented on second.html
> +                <section class="story"></section>
```suggestion
                <section class="story hidden"></section>
```

2023-03-25 18:17 UTC, terrifricker commented on style.css
Add
```
.hidden {
    display: none;
}
```
to end of style.css file.

2023-03-25 18:17 UTC, terrifricker commented on style.css
> +    display: none;
```suggestion
```

2023-03-25 18:17 UTC, terrifricker commented on style.css
> +    display: none;
Remove display: none; form story class and instead create a new class named 'hidden' to the bottom of this file.

2023-03-27 19:28 UTC, terrifricker approved these changes
Approving as is!  Any changes decided on can be done as refactoring.

2023-03-27 19:28 UTC, merged