Meek/basic UI styling
chingu-voyages/v43-tier1-team-08 pull request #67
Opened 2023-03-29 18:17 UTC by mmsaki

## Description

- Match style closely to what is specified in Figma frames.
- Responsive design for narrow screen
- Added images
- Added starting fonts

## Related Issue

Closes #65 

## Acceptance Criteria

- [x] Match Figma design
- [x] Fix responsive issues

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓  | :bug: Bug fix              |
|  ✓  | :sparkles: New feature     |
|  ✓  | :hammer: Refactoring       |

## Updates

### Before

<img width="819" alt="Screenshot 2023-03-29 at 12 07 29 PM" src="https://user-images.githubusercontent.com/98189596/228620257-5b31898d-2a75-4ac0-9e21-3a052de27695.png">

### After

<img width="961" alt="Screenshot 2023-03-29 at 12 42 48 PM" src="https://user-images.githubusercontent.com/98189596/228624848-c20fc4bd-9434-456e-992a-459c6d29638b.png">

### Next steps

- Improve design to a more playful colorful and gameish.
- Feedback and updates can be added on figma

2023-03-29 19:30 UTC, terrifricker reviewed
I've started going through, but I'm not on my own computer with VSCode available to work through the major css.  It will be nice to have it all consistent.

2023-03-29 19:30 UTC, terrifricker commented on app.js
In the future, formatting changes should be isolated into their own pull request.  It was very difficult to see where actual changes in the code were made.  I had to go line by line, every line, and visually inspect for changes.  Sometimes the sections were long enough that I was not able to see the lines on the same screen even.

2023-03-29 19:30 UTC, terrifricker commented on data/data.json
Again, this should have been in a separate formatting change pull request.  It is impossible to know if a single character was changed in this file.

2023-03-29 19:30 UTC, terrifricker commented on instructions.html
> +				<a href="play.html" onclick="document.location='play.html'">Play</a>
```suggestion
				<a href="play.html">Play</a>
```

2023-03-29 19:30 UTC, terrifricker commented on ourteam.html
> +				<a href="play.html" onclick="document.location='play.html'">Play</a>
```suggestion
				<a href="play.html">Play</a>
```

2023-03-30 02:17 UTC, mmsaki commented on instructions.html
> +				<a href="play.html" onclick="document.location='play.html'">Play</a>
thanks for that

2023-03-30 02:37 UTC, mmsaki commented on data/data.json
no content has changed on this file i think my formatter might have picked up some linting issues and auto-formatted

2023-03-30 02:55 UTC, mmsaki commented on app.js
Hey thanks for the feedback. I agree! Formatting does make it hard to review important changes. Githib actually has some nice features to hide white space formating and settings to make that easy for you. [See this article](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project). Here's the tip i got from the article 

https://docs.github.com/assets/cb-237160/mw-1000/images/help/desktop/diff-selection.webp

2023-03-30 04:15 UTC, terrifricker commented on app.js
Thank you!!

2023-03-30 04:20 UTC, terrifricker commented on app.js
Argh!  I don't use desktop.  Guess I need to change that.

2023-03-30 05:32 UTC, terrifricker requested changes
We need to work on the media query.  Here are the images I have on Chrome Dev tools for a screen width of 360px.  Either a hamburger menu or flex-direction column as a start.

![Screen Shot 2023-03-29 at 10 25 55 PM](https://user-images.githubusercontent.com/51532684/228738604-e82bfa8b-751f-4079-814c-fbb53bd782ad.png)
![Screen Shot 2023-03-29 at 10 26 05 PM](https://user-images.githubusercontent.com/51532684/228738607-e76e9d64-82c6-45cc-ad85-d15fbd1d9c32.png)
![Screen Shot 2023-03-29 at 10 26 18 PM](https://user-images.githubusercontent.com/51532684/228738609-869d0c99-2fd9-45b4-87e1-220a402eb721.png)

2023-03-30 05:32 UTC, terrifricker commented on styles.css
> +	display: flex-box;
```suggestion
```

2023-03-30 05:32 UTC, terrifricker commented on styles.css
> +	display: flex-box;
flex-box is not a display option, and you wouldn't want this on * global anyway.

2023-03-30 05:32 UTC, terrifricker commented on styles.css
> +html body {
The selector html body means the body element within html which is just the body element.  html is not needed.
```suggestion
body {
```

2023-03-30 05:32 UTC, terrifricker commented on styles.css
> +	text-align: center;
```suggestion
```
not need now that .logo is an image.

2023-03-30 05:32 UTC, terrifricker commented on styles.css
> +	background-color: rgb(255, 255, 255, 0);
why not background-color white or not defined instead of transparent white?

2023-03-30 05:34 UTC, terrifricker commented on data/data.json
What are you using as a formatter/linter?  I use Prettier and ESLint.

2023-03-30 05:41 UTC, mmsaki commented on styles.css
> +	display: flex-box;
not sure who added flexbox, but can look into that

2023-03-30 05:57 UTC, mmsaki commented
@terrifricker I was aiming for 390px screen width to start with. I agree that a hambager menu. Only reason I didn't add a hamburger menu on is PR is because it has not been specified on the design yet. Thank you for catching that. Also, the browser's sometimes resize with extreme zoom out not sure exactly how to fix that, but you should notice the same thing for other websites on your second image.

2023-03-30 14:14 UTC, terrifricker approved these changes

2023-03-30 14:15 UTC, terrifricker approved these changes
Woo hoo!

2023-03-30 14:20 UTC, terrifricker commented
>  Also, the browser's sometimes resize with extreme zoom out not sure exactly how to fix that, but you should notice the same thing for other websites on your second image.

You're exactly right!  How weird!

2023-03-30 14:39 UTC, merged